BotChallenge.cpp
	CommonData.h
	Game.h
		Board.h
			Move.h
		Player.h
			Board.h
			Move.h
		HumanPayer.h
			Player.h
		ComputerPlayer.h
			Player.h
			InterativeDeepening.h
				Board.h
				Move.h
				AlphaBetaPruning.h
					MoveValuePair.h
						Move.h
					Board.h
